name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal:latest
    strategy:
      matrix:
        node: ['14']
    name: Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: yarn install
      - run: yarn fmt-check
      - run: yarn lint
      - run: yarn test
